require('config.options').config()
require('config.keymaps').config()
require('config.autocmds').config()

require('plugins.dressing-nvim').config()
require('plugins.which-key').config()
require('plugins.legendary-nvim').config()
require('plugins.nvim-treesitter').config()
require('plugins.nvim-lualine').config()
require('plugins.nvim-telescope').config()
require('plugins.nvim-cmp').config()
require('plugins.nvim-lspconfig').config()
require('plugins.nvim-spectre').config()
require('plugins.vim-sexp').config()
require('plugins.conjure').config()
